---
title: "Reprex"
author: 
    name: "Monique Hernandez"
    email: mahernandez@ucsb.edu
    affiliation: 
    - University of California, Santa Barbara
    - Masters of Environmental Data Science, 2027
    - B.S. in Environmental Studies, 2025
date: "Augustt 20, 2026"
toc: true
format:
  html:
    theme: "pulse"
    other-links:
      - text: Course Website EDS 221 
        href: https://eds-221-programming-m26.github.io/course-materials/day9.html
      - text: Monique's website
        href: moniqueallyson.github.io
execute:
  message: false
  warning: false
---
[click here for github link](https://github.com/moniqueallyson/eds221day9) 

```{r, message=FALSE}

library(tidyverse)
library(reprex)

mack_creek_vertebrates <- read_csv("data/AS00601.csv")

```

## Example 1

```{r}
mack_creek_lengths <- mack_creek_vertebrates |>
  select(YEAR:SAMPLEDATE) |>
  filter(SECTION == "CC",
         !is.na(SPECIES)) |>
  summarize(mean_length_cm = mean(LENGTH1, na.rm = TRUE),
            sd_length_cm = sd(LENGTH1, na.rm = TRUE),
            .by = species)
```

### Set-up the databy taking just a few rows and columns calling dput()
```{r}
mack_creek_vertebrates[1:3, c("LENGTH1", "SPECIES")] |> 
    dput()
mack_creek_ouput <- structure(list(LENGTH1 = c(58, 61, 89), SPECIES = c("ONCL", "ONCL", 
"ONCL")), row.names = c(NA, -3L), class = c("tbl_df", "tbl", 
"data.frame"))

```


```{r}
mack_creek_vertebrates <- read_csv("data/AS00601.csv")
mack_creek_lengths <- mack_creek_vertebrates |>
    summarize(sd_length_cm = sd(LENGTH1),
            .by = species)

```

## How to fix example 1 - reproducibilty
Step 1. Copy the code
Step 2. Call the reprex() function

```{r}
library(tidyverse)

mack_creek_vertebrates[1:3, c("LENGTH1", "SPECIES")] |> 
    dput()
mack_creek_ouput <- structure(list(LENGTH1 = c(58, 61, 89), SPECIES = c("ONCL", "ONCL", 
"ONCL")), row.names = c(NA, -3L), class = c("tbl_df", "tbl", 
"data.frame"))
mack_creek_lengths <- mack_creek_vertebrates |>
    summarize(sd_length_cm = sd(LENGTH1),
            .by = species)

```

### Example 2

```{r}
library(tidyverse)


mack_creek_vertebrates <-  structure(list(LENGTH1 = c(58, 61, 89), SPECIES = c("ONCL", "ONCL", 
"ONCL")), row.names = c(NA, -3L), class = c("tbl_df", "tbl", 
"data.frame"))
mack_creek_vertebrates |>
  filter(SPECIES == "ONCL") +
  ggplot(mapping = aes(x = LENGTH1, y = WEIGHT))

```
